# Generated by Django 4.0.1 on 2022-01-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.IntegerField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, unique=True),
        ),
    ]
