# Generated by Django 4.0.1 on 2022-01-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.IntegerField(error_messages={'unique': 'Please enter a unique product Id.'}, unique=True),
        ),
    ]
